### ISSUE TITLE
New Icon Cielo Elo

### ISSUE THREAD

**Issue by jgautheron** [vendocrat/PaymentFont#30]
A popular Brazilian credit card.
http://www.turistamalemolente.com.br/wp-content/uploads/2011/10/Cartao-Elo-da-Cielo-conheca-essa-novidade.jpg
https://www.cielo.com.br/vem-pra-cielo

**Comment by igorsantos07** [comment]
This seems invalid. Elo icon is right there:
![2015-04-29-13 40 37-selection-d6f1](https://cloud.githubusercontent.com/assets/532299/7396175/5edb3942-ee75-11e4-9082-ada31fffd1f7.png)
