### ISSUE TITLE
Hey I got a few Icon request for the german market

### ISSUE THREAD

**Issue by panploenes** [vendocrat/PaymentFont#35]
I tried myself in making these icons, unfortunately I am not 100% I did everything right.
But here are some suggestions:
Lastschrift
![lastschrift](https://cloud.githubusercontent.com/assets/8298538/6315980/d870f88c-ba13-11e4-9b0a-9413c7e9c139.png)
A German Bank Transfer Logo named: Bank Überweisung

**Comment by AlexanderPoellmann** [comment]
Hallo, EC ist bereits mit von der Partie (.pf-ec), Bank-Überweisung kommt demnächst! Bitte nächstes mal ein Logo/Issue zwecks Organisation ;)
