### ISSUE TITLE
Please add German icons

### ISSUE THREAD

**Issue by Repalogic** [vendocrat/PaymentFont#41]
Can you please add some German payment icons?

Vorkasse (payment before delivery, very typical in Germany)
Bar bei Abholung (Cash on pickup)
Nachnahme (Cash on delivery, very typical in Germany)
Ratenkauf (Payment with instalment plan)

**Comment by panploenes** [comment]
+ 1  Would help but tried myself at editing font and failed :(

**Comment by AlexanderPoellmann** [comment]
@Repalogic Wir haben zum Thema Übersetzungen einen eigenen Thread, bei dem du ohnehin auch schon gepostet hast. Ich überlege ab v2 eine solche CSS-basierte Lösung zur Verfügung zu stellen, anstatt den Font mit übersetzten Icons zu überladen.

@panploenes I'm considering a CSS-based solution for the translation issue from v2 onwards, as I don't want to overload PaymentFont with several translated icons. Any other suggestions are of course very welcome here: https://github.com/vendocrat/PaymentFont/issues/32
