### ISSUE TITLE
Great British Pound (£) misspelled class name

### ISSUE THREAD

**Issue by joejoinerr** [vendocrat/PaymentFont#58]
The class name for the British Pound (£) symbol is in the CSS as `.pf-gpb`, but should be `.pf-gbp` (for **G**reat **B**ritish **P**ound).

**Comment by AlexanderPoellmann** [comment]
Oops, my bad. Consider it fixed!

**Comment by AlexanderPoellmann** [comment]
Published a minor releas (v1.1.2) already.

**Comment by phpcodemonkey** [comment]
It's still the wrong way round on the main website http://paymentfont.io/#pf-gpb

**Comment by AlexanderPoellmann** [comment]
It's working for me, just checked it on my mobile. Please refresh your browser and/or empty your browsers cache.

![paymentfont](https://cloud.githubusercontent.com/assets/6631793/7339044/ed5e3136-ec60-11e4-8c3a-a5257d68376d.png)
