### ISSUE TITLE
Shopping Cart Icons

### ISSUE THREAD

**Issue by byronyasgur** [vendocrat/PaymentFont#64]
Just an idea. Your collection is amazing but wouldn't a few shopping cart icons complete the set nicely. Eg Cart Checkout Account Wishlist Delivery Calculator etc. Just a thought .... I'm doing discovery on a couple of ecommerce projects and I'll definitely be using this set. Thanks and well done

**Comment by AlexanderPoellmann** [comment]
Hi, I'm working on a dedicated e-commerce/shopping font as I believe such icons just don't fit into a payment provider/method font.
