### ISSUE TITLE
Icons not working in Firefox

### ISSUE THREAD

**Issue by josiahsprague** [vendocrat/PaymentFont#83]
I'm having trouble getting these icons to work in Firefox v38, both on http://paymentfont.io/ and in my own app. I checked the common `@font-face` issue in Firefox, regarding the `Access-Control-Allow-Origin "*"` header. My fonts are being served with that header, so that isn't the issue.

**Comment by KrzysiekF** [comment]
I have the same trouble.

**Comment by josiahsprague** [comment]
I never got to the bottom of it, but tested on Firefox in BrowserStack with no issues. Uninstalling and reinstalling Firefox locally resolved the issue (same version). No idea what was causing it though.

**Comment by KrzysiekF** [comment]
ok ... thank you @josiahsprague for your answer

**Comment by josiahsprague** [comment]
Closing since this issue is no longer relevant to me and it's clogging up my GitHub issues. If someone wants to resume discussion on it at some point, feel free to reopen the issue.
